functionsDirectory = "C:\\Users\\11 PRO.DESKTOP-OQHKL3C\\Documents\\adminapp\\eauksion-app_1\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "C:\\Users\\11 PRO.DESKTOP-OQHKL3C\\Documents\\adminapp\\eauksion-app_1\\eauksion-app"
publishOrigin = "config"
functions = "C:\\Users\\11 PRO.DESKTOP-OQHKL3C\\Documents\\adminapp\\eauksion-app_1\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]