[build]
  command = "npm install"
  publish = "eauksion-app"
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
[[redirects]]
  from = "/api/front/lots"
  to = "/.netlify/functions/fetch-lots"
  status = 200
  force = true

[[redirects]]
  from = "/telegram-settings"
  to = "/.netlify/functions/telegram-settings"
  status = 200
  force = true

[[redirects]]
  from = "/send-telegram"
  to = "/.netlify/functions/send-telegram"
  status = 200
  force = true

[[redirects]]
  from = "/favorites"
  to = "/.netlify/functions/favorites"
  status = 200
  force = true

# Catch-all for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
