[build]
  command = ""
  publish = "eauksion-app"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/front/lots"
  to = "/.netlify/functions/fetch-lots"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
